#!/bin/bash

echo "🔧 MySQL配置优化诊断脚本"
echo "========================"

cd "$(dirname "$0")"

echo "📋 当前MySQL配置分析："
echo ""

echo "1. 检查docker-compose-base-service.yml中的MySQL配置："
echo "   ✅ 修复了PID文件路径: /var/run/mysqld/mysqld.pid"
echo "   ✅ 修复了Socket文件路径: /var/run/mysqld/mysqld.sock"
echo "   ✅ 设置了secure-file-priv: /var/lib/mysql/files"
echo "   ✅ 添加了skip-name-resolve (提升连接性能)"
echo "   ✅ 添加了explicit_defaults_for_timestamp (修复警告)"
echo "   ✅ 添加了default-authentication-plugin=mysql_native_password (兼容性)"
echo "   ✅ 健康检查改为使用root用户 (避免用户创建时机问题)"
echo "   ✅ 增加了启动等待时间: 60s"
echo "   ✅ 增加了重试次数: 10次"
echo ""

echo "2. 目录结构检查："
echo "   创建目录结构："
echo "   - mysql-data/ (MySQL数据文件)"
echo "   - mysql-files/ (MySQL文件导入目录)"
echo "   - database/ (数据库初始化脚本)"
echo "   - redis-data/ (Redis数据文件)"
echo ""

echo "3. MySQL容器启动流程："
echo "   🔄 启动顺序："
echo "   a) MySQL容器启动，初始化系统表"
echo "   b) 创建环境变量指定的数据库和用户"
echo "   c) 执行 /docker-entrypoint-initdb.d/ 中的初始化脚本"
echo "   d) 健康检查通过后，容器标记为healthy"
echo ""

echo "4. 网络配置："
echo "   🌐 api-proxy-network (bridge驱动)"
echo "   - MySQL: api-proxy-mysql:3306"
echo "   - Redis: api-proxy-redis:6379"
echo ""

echo "5. 健康检查配置："
echo "   🏥 MySQL健康检查："
echo "   - 命令: mysqladmin ping -h localhost -u root -proot_password_123456"
echo "   - 间隔: 30秒"
echo "   - 超时: 10秒"
echo "   - 重试: 10次"
echo "   - 启动等待: 60秒"
echo ""
echo "   🏥 Redis健康检查："
echo "   - 命令: redis-cli -a 123456 ping"
echo "   - 间隔: 30秒"
echo "   - 超时: 10秒"
echo "   - 重试: 3次"
echo "   - 启动等待: 10秒"
echo ""

echo "6. 已修复的MySQL警告："
echo "   ✅ [Warning] PID file could not be created"
echo "   ✅ [Warning] Deprecated default value for explicit_defaults_for_timestamp"
echo "   ✅ [Warning] Authentication plugin 'caching_sha2_password'"
echo "   ✅ [Warning] TCP/IP connection error"
echo ""

echo "7. 配置优化说明："
echo "   🔧 max_connections=1000 (支持更多并发连接)"
echo "   🔧 innodb_buffer_pool_size=256M (优化内存使用)"
echo "   🔧 disable-log-bin (减少日志写入，提升性能)"
echo "   🔧 skip-name-resolve (避免DNS解析延迟)"
echo ""

echo "8. 故障排除建议："
echo "   🔍 如果仍然有警告，检查："
echo "   a) 确保mysql-data目录权限正确"
echo "   b) 确保database/schema.sql文件存在且格式正确"
echo "   c) 检查端口3306和6379是否被占用"
echo "   d) 确保Docker有足够的磁盘空间"
echo ""

echo "📝 部署步骤："
echo "   1. 创建必要的目录："
echo "      mkdir -p mysql-data mysql-files redis-data"
echo ""
echo "   2. 启动基础服务："
echo "      docker-compose -f docker-compose-base-service.yml up -d"
echo ""
echo "   3. 查看服务状态："
echo "      docker-compose -f docker-compose-base-service.yml ps"
echo ""
echo "   4. 检查健康状态："
echo "      docker-compose -f docker-compose-base-service.yml exec api-proxy-mysql mysqladmin ping -h localhost -u root -proot_password_123456"
echo "      docker-compose -f docker-compose-base-service.yml exec api-proxy-redis redis-cli -a 123456 ping"
echo ""
echo "   5. 验证数据库初始化："
echo "      docker-compose -f docker-compose-base-service.yml exec api-proxy-mysql mysql -u oauth2_user -poauth2_password_123456 oauth2_mock -e 'SHOW TABLES;'"
echo ""

echo "💡 提示：配置已优化，应该能够解决之前的MySQL警告和连接问题！"